export const API_PATHS = {
    UPDATE_USER: '/api/user/update',
    CHECK_ORGANIZATION: '/api/organization/check-organization',
    GET_ORGANIZATION: '/api/organization/get-organizations',
    SAVE_ORGANIZATION: '/api/organization/save-organization',
    GET_PROJECTS: '/api/project/get-projects',
    ADD_PROJECT: '/api/project/add-project',
    SAVE_BPMN: '/api/bpmn/save-bpmn',
    GET_BPMN_FILES: '/api/bpmn/get-bpmn-files',
    INVITE_STAKEHOLDER: '/api/stakeholder/invite-stakeholder',
    RESEND_STAKEHOLDER_INVITATION: '/api/stakeholder/resend-invite',
    ACCEPT_STAKEHOLDER_INVITATION: '/api/stakeholder/accept-invite',
    ACCEPT_INVITATION: '/api/invitation/accept',
    GET_BPMN_STAKEHOLDERS: '/api/stakeholder/get-bpmn-stakeholders',
    GET_PENDING_BPMN_STAKEHOLDERS: '/api/invitation/get-pending-bpmn-stakeholders',
    REVOKE_STAKEHOLDER_BPMN_ACCESS: '/api/stakeholder/revoke-bpmn-access',
    INVITE_MEMBER: '/api/member/invite-member',
    RESEND_MEMBER_INVITATION: '/api/member/resend-invite',
    GET_MEMBERS: '/api/member/get-members',
    GET_PENDING_MEMBERS: '/api/invitation/get-pending-members',
    REVOKE_MEMBER_ACCESS: '/api/member/revoke-access',
};