name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Add remote
      - name: Add Remote
        run: git remote add target https://oauth2:${{ secrets.TARGET_TOKEN }}@${{ secrets.TARGET_URL }}
      
      # Push branches
      - name: Push Branches to GitLab
        run: git push target --all --prune --force

      # Push tags
      - name: Push Tags to GitLab
        run: git push target --tags --prune --force
